{% set name = "py2dm" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/py2dm-{{ version }}.tar.gz
  sha256: fa16812292abb8162a046089324b568fdd654198d10fd8430df031f8b1eb3209

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setupstools
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - py2dm

about:
  home: https://github.com/leonhard-s/Py2DM
  summary: Read and write 2DM mesh files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bedaro
    - optiz0r
